### ISSUE TITLE
os._exit(1) in python file imported to R and executed causes R to experience a fatal error

### ISSUE THREAD

**Issue by Argzero** [rstudio/reticulate#1238]
![image](https://user-images.githubusercontent.com/3894611/178557666-05727b0a-4f08-4c41-97a0-d643aad02c34.png)

**Comment by t-kalinowski** [comment]
Hi, can you please provide additional information about your environment? Ideally something that would allow me to reproduce the error on my machine.

**Comment by shivam7898** [comment]
I am not the original poster. However, I am aware of this issue. So, attaching reprex:

    ---
    title: "Abort on os._exit(1)"
    output: html_document
    ---
    
    ```{r 'setup'}
    library(reticulate)
    reticulate::use_python("C:\\Softwares\\Python\\Python310\\python.exe", required = TRUE)
    #reticulate::use_python_version("3.10.5")
    ```

```python
# Python Chunk
import os
# Caution: Following code will completely terminate the session
os._exit(1)

```

Above code, if executed in any `Rmd` file will result in complete termination of R Session. 

To provide some more context about it:

```python
# None of the following will prevent the Python code from further execution
assert(False)
exit(1)
quit(1)
sys.exit(1)
raise SystemExit
print("This Prints!")

```

Unlike R chunks, where `stopifnot(FALSE)` will immediately stops the execution, currently there is no way  in Python chunk to stop execution if a condition evaluates to `False` (as far as I have checked). 
At one end `assert()`, `exit()`, `quit()`, `sys.exit()` etc. throws `ERROR` but do not stop the execution of next line of code. On the other extreme end `os._exit(1)` completely terminates the session. 

Personally, I believe that at least `assert(False)` and `sys.exit(1)` should stop the script execution and `os._exit(1)` should not terminate the session completely. 

<details>
  <summary>Click to expand!: sessionInfo() & py_config()</summary>

```r
sessionInfo()

## R version 4.2.1 (2022-06-23 ucrt)
## Platform: x86_64-w64-mingw32/x64 (64-bit)
## Running under: Windows 10 x64 (build 19044)
## 
## Matrix products: default
## 
## locale:
## [1] LC_COLLATE=English_India.utf8  LC_CTYPE=English_India.utf8    LC_MONETARY=English_India.utf8
## [4] LC_NUMERIC=C                   LC_TIME=English_India.utf8    
## 
## attached base packages:
## [1] stats     graphics  grDevices utils     datasets  methods   base     
## 
## other attached packages:
## [1] reticulate_1.25
## 
## loaded via a namespace (and not attached):
##  [1] compiler_4.2.1  here_1.0.1      Matrix_1.4-1    rprojroot_2.0.3 tools_4.2.1     Rcpp_1.0.9     
##  [7] grid_4.2.1      knitr_1.39      xfun_0.31       jsonlite_1.8.0  png_0.1-7       lattice_0.20-45
```

```r
py_config()
## python:         C:/Softwares/Python/Python310/python.exe
## libpython:      C:/Softwares/Python/Python310/python310.dll
## pythonhome:     C:/Softwares/Python/Python310
## version:        3.10.5 (tags/v3.10.5:f377153, Jun  6 2022, 16:14:13) [MSC v.1929 64 bit (AMD64)]
## Architecture:   64bit
## numpy:          C:/Softwares/Python/Python310/Lib/site-packages/numpy
## numpy_version:  1.23.1
## 
## NOTE: Python version was forced by use_python function
```

</details>

**Comment by kevinushey** [comment]
For the original post, this seems like the intended behavior. You asked Python to quit the session, and so it quit the session. Since Python is embedded within the R session, exiting Python implies exiting R.

> Personally, I believe that at least assert(False) and sys.exit(1) should stop the script execution and os._exit(1) should not terminate the session completely.

How are you running R? Are you executing code within RStudio, or something else?

Assuming that you're using RStudio, I think the issue you're reporting is that if you run the following code in one "block":

```
raise ValueError("Oh no!")
1 + 1
```

then `1 + 1` is executed, even if an error occurs.

The standalone `python` interpreter has the same behavior as us here, but other "smart" REPLs (like `ipython`) stop code execution after an error or exception occurs.

**Comment by shivam7898** [comment]
> Since Python is embedded within the R session, exiting Python implies exiting R.

I provided the first part of code because the original poster did not supply the reprex. I agree with the exit from Python on `os._exit(1)`. I would prefer to not exit R so completely. However, I do not know how difficult it would be to separate the integration of R and Python. So I am not complaining there.

You are correct in both of your assumptions: 

>...Are you executing code within RStudio...

Yes.

>... `1 + 1` is executed, even if an error occurs.

Yes, I believe that a python chunk should behave similar to a R chunk

```python
# Python chunk executes print statement even after assertion error
assert(False)
print("Hi")

## AssertionError: 
## Hi
```
```r
# R chunk does not executes the print statement after stopifnot() throws error
stopifnot(FALSE)
print("Hi")

## Error: FALSE is not TRUE
```

Please let me know if I am attaching a separate issue here. I would stop. Thank you all for the work on such an excellent package :)
