### ISSUE TITLE
pyscreenshot.err.FailedBackendError

### ISSUE THREAD

**Issue by leechaowen** [rstudio/reticulate#1246]
i need import pyscreenshot to take screen shot,but fail.  any idea?

```
library(reticulate)

library(magick)

pyscreenshot<-import("pyscreenshot")

TheFullScreenImage<-pyscreenshot$grab()

input <- image_read(TheFullScreenImage)
```

**run result:**

```
> library(tesseract)
> 
> library(reticulate)
> 
> library(magick)
> 
> pyscreenshot<-import("pyscreenshot")
> 
> TheFullScreenImage<-pyscreenshot$grab()
Error in py_call_impl(callable, dots$args, dots$keywords) : 
  pyscreenshot.err.FailedBackendError: All backends failed!
```

Thanks your support.

**Comment by leechaowen** [comment]
same issue ,still  using pyscreenshot.I have  the following Python script takeScreenShot.py:

```
import pyscreenshot
def TakeScreenshot(x1,y1,x2,y2):
    image = pyscreenshot.grab(bbox=(x1,y1,x2,y2))
    return(image)
```
Then source the script and call the TakeScreenshot() function as follows:

```
library(reticulate)

library(magick)

source_python("takeScreenShot.py")

CatchImage=TakeScreenshot(1078,392,1428,481)

input <- image_read(CatchImage)
```

**run result**

```
> library(reticulate)
> 
> library(magick)
> 
> source_python("takeScreenShot.py")
> 
> CatchImage=TakeScreenshot(1078,392,1428,481)
Error in py_call_impl(callable, dots$args, dots$keywords) : 
  pyscreenshot.err.FailedBackendError: All backends failed!
> 

```

I really need the screenshot function.  but it seems R not support screenshot. so need depend on python.

**Comment by leechaowen** [comment]
```
> reticulate::py_config()
python:         C:/Program Files/Python310/python.exe
libpython:      C:/Program Files/Python310/python310.dll
pythonhome:     C:/Program Files/Python310
version:        3.10.5 (tags/v3.10.5:f377153, Jun  6 2022, 16:14:13) [MSC v.1929 64 bit (AMD64)]
Architecture:   64bit
numpy:          C:/Users/86158/AppData/Roaming/Python/Python310/site-packages/numpy
numpy_version:  1.23.1

NOTE: Python version was forced by use_python function
```

**Comment by leechaowen** [comment]
<img width="815" alt="image" src="https://user-images.githubusercontent.com/44858442/181292109-998e4104-d4ed-40a3-91b7-0ca248ba375b.png">

**Comment by t-kalinowski** [comment]
Hi, thanks for filing.

It looks you installed pyscreenshot successfully and reticulate is able to import and use the python module correctly. The error is being raised from pyscreenshot because it can't find an appropriate backend. If you take a look here: https://github.com/ponty/pyscreenshot, it looks like you also need to take additional steps to configure or point it at an appropriate backend. The project repo also mentions that the entire project is obsolete and deprecated, and they recommend using Pillow directly today.

Closing because I don't think this is a reticulate issue. (i.e., you'd encounter the same hurdles, and require the same solutions, if you were working directly in Python).
