### ISSUE TITLE
Error when testing the type for a pandas dataframe (Error in py_call_impl: TypeError: to_html() missing 1 required positional argument: 'self')

### ISSUE THREAD

**Issue by vnijs** [rstudio/reticulate#1249]
Have been using reticulate for several years in a larger shiny / knitr app and it has worked well. Hadn't used it with students for several months and am now getting the error below. Getting the type of basic python objects still works fine. However, when trying to get check the type of a pandas data frame there is a problem. 

Since I haven't changed the application and, with this exception, it still all works fine I can assume there is an issue with reticulate, knitr, or some other dependency. I'm planning to revert different package versions until it starts working again but I was hoping you might have some inspiration to share on which package this error might be most likely to originate in. Any suggestions would be much appreciated

![image](https://user-images.githubusercontent.com/2998956/182551671-4ba783fc-32e2-4b84-b864-ba92d7ad43ca.png)

**Comment by t-kalinowski** [comment]
Hi, thanks for filing. I am able to reproduce this on my side. This error is specific to 
an interaction with the latest pandas and the knitr engine that reticulate provides. 

Specifically, the error is being emitted from [this line](https://github.com/rstudio/reticulate/blob/b5ee7e9678bd0bc3f9dcd9d27ce60f8814fe030d/R/knitr-engine.R#L569), where we call `value$to_html()`. Here, `value` is the return value from `type(pt)`, that is, the class definition/constructor object `pd.DataFrame`. We enter this branch because the `pd.DataFrame` does have the attribute `_repr_html_`, but it is actually a method meant to be invoked from an instance.

**Comment by shivam7898** [comment]
I also faced similar issue. I was able to workaround it by wrapping the output of `type()`  in print i.e. `print(type(x))`.

**Comment by vnijs** [comment]
Thanks for the suggestion @shivam7898. Unfortunately, I'm still seeing the problem.

![image](https://user-images.githubusercontent.com/2998956/182704948-4db2d1b4-eb54-451c-a4d6-23af8decd067.png)

**Comment by t-kalinowski** [comment]
@vnijs I just merged a commit related to this issue. Can you please install the dev version of reticulate and let me know if it fixes your issue?

```R
remotes::install_github("rstudio/reticulate")
```

**Comment by vnijs** [comment]
@t-kalinowski Seems to work fine! Thanks
