### ISSUE TITLE
Sympy's lambdify not working

### ISSUE THREAD

**Issue by tamas-ferenci** [rstudio/reticulate#1356]
Consider the following minimal reproducible example:

    sympy <- reticulate::import("sympy")
    x <- sympy$Symbol("x")
    sympy$lambdify(x, x)

It returns cryptic (at least to me...) `Error: AttributeError: 'NoneType' object has no attribute 'f_locals'` error message.

**Comment by t-kalinowski** [comment]
Hi, thanks for the report. I can reproduce this locally.

It looks like [`sympy.lambdify()`](https://github.com/sympy/sympy/blob/aea506d5a3bb36f499da8e3c5cc0933ddde20a8a/sympy/utilities/lambdify.py#L850) calls `inspect.currentframe()` and assumes that what comes back is a python frame:  


The docs for that function indicate that [`currentframe()`](https://docs.python.org/3/library/inspect.html#inspect.currentframe) can return `None`

The seems like something that should be patched in sympy, so that `lambdify()` does not raise an error when `currentframe()` returns `None`.

This is the first report (to my knowledge) of this error with reticulate in the years it's been out; it would appear that this kind of runtime stack introspection is uncommon in Python libraries. 

However, if it becomes a common problem, we can investigate having reticulate introducing a "fake" python frame in the call stack when running python code, right now it just evaluates the code directly, not as part of a stack. 

For now, you can manually introduce a frame for sympy to find by wrapping `lambdify` in a simple wrapper function that just passes through its args, like this:

```r
sympy <- reticulate::import("sympy")
x <- sympy$Symbol("x")

lambdify <- py_run_string(
"import sympy
def lambdify(*args, **kwargs):
  return sympy.lambdify(*args, **kwargs)
", local = TRUE)$lambdify

f <- lambdify(x, x)
f(1)
```

**Comment by tamas-ferenci** [comment]
Thank you very much @t-kalinowski! Shall I report this to `sympy`...? (I have no knowledge in Python.)

I appreciate the workaround, however, when running `f <- lambdify(x, x)`, it gives an `Error: NameError: name 'sympy' is not defined` error message to me.

**Comment by t-kalinowski** [comment]
Apologies, I've updated the snippet above, should work now. 

Yes, I think opening an issue on the sympy would be helpful :)

**Comment by tamas-ferenci** [comment]
Thank you very much, it now works perfectly! I opened an issue at `sympy` (https://github.com/sympy/sympy/issues/24951).

**Comment by varunseth5788** [comment]
this issue is open  can i contribute.

**Comment by t-kalinowski** [comment]
Hi @varunseth5788 What do you have in mind?
