### ISSUE TITLE
a new r-reticulate env is created at each new R session if env was previously deleted

### ISSUE THREAD

**Issue by dsolito** [rstudio/reticulate#1374]
Hi,
If I delete the r-reticulate env, each time I restart a new Rstudio session, a r-reticulate env is re created.
Why? And this is done with python 3.8 version. Where can I manage this behaviour?
Thanks

**Comment by dfalbel** [comment]
We have made substantial changes to Python installation management in the newly released v1.31, it would be great if you could update reticulate and see if the problem is fixed.

You can find additional documentation on managing python installations [here](https://rstudio.github.io/reticulate/articles/versions.html).
