### ISSUE TITLE
Knit/Render of python plot in R code chunk is produced outside the document

### ISSUE THREAD

**Issue by rressler** [rstudio/reticulate#1397]
The following code creates a plot which appears inline following the code chunk when run interactively in RStudio.
However, when when knit/render, the plot appears in a pop-up window but not in the html document.

```{r}
library(reticulate)
library(palmerpenguins)
sns <- import('seaborn')
plt <- import('matplotlib.pyplot')
pd <- import('pandas')

pen_plot <- sns$pairplot(r_to_py(penguins), hue = 'species')
plt$show()
```
Plots in Python code chunks render fine. Should only python code chunk be used for creating plots or is there a setting to put the figures into the output document?

Thanks,
Richard

**Comment by t-kalinowski** [comment]
Thanks for filing. This is a current limitation of the interface. Within the reticulate knitr engine, we install hooks to customize `plt.show()` so that the figure appears in the rendered document. When evaluating `plt$show()` outside the reticulate knitr engine (that is, not in a python chunk), the hooks don't get an opportunity to run so you get the default matplotlib behavior (showing the plot in a pop-up window).

Until this is fixed, you can work around this limitation by calling `plt.show()` in an (invisible) python chunk.

````

```{r}
library(reticulate)
library(palmerpenguins)
sns <- import('seaborn')
plt <- import('matplotlib.pyplot')
pd <- import('pandas')

pen_plot <- sns$pairplot(r_to_py(penguins), hue = 'species')
```

```{r, eval=FALSE, echo = TRUE}
plt$show()
```

```{python, echo = FALSE}
import matplotlib.pyplot as plt
plt.show()
```

````

**Comment by rressler** [comment]
Thanks for the quick response and great explanation!
