### ISSUE TITLE
pymc issue when knitting a document

### ISSUE THREAD

**Issue by cderv** [rstudio/reticulate#1508]
````markdown
---
title: "Test"
output: html_document
---

```{python}
import pymc as pm
```
````

When rendering this errors

````
==> rmarkdown::render('test.Rmd');

  |....................................................| 100% [unnamed-chunk-1]

processing file: test.Rmd

Quitting from lines 9-10 [unnamed-chunk-1] (test.Rmd)
Error in `py_call_impl()`:
! TypeError: decode() argument 'encoding' must be str, not None
Run `reticulate::py_last_error()` for details.
Backtrace:
  1. rmarkdown::render("C:/Users/chris/Documents/test.Rmd", encoding = "UTF-8")
  2. knitr::knit(knit_input, knit_output, envir = envir, quiet = quiet)
  3. knitr:::process_file(text, output)
  8. knitr:::process_group.block(group)
  9. knitr:::call_block(x)
     ...
 13. knitr (local) engine(options)
 14. reticulate::eng_python(options)
 15. reticulate:::py_compile_eval(snippet, compile_mode)
 18. builtins$eval(compiled, globals, locals)
 19. reticulate:::py_call_impl(callable, call_args$unnamed, call_args$named)
                                                                                                            
Exécution arrêtée
````

In REPL it works ok 

````
> reticulate::repl_python()
Python 3.11.1 (C:/Users/chris/Documents/.virtualenvs/r-reticulate/Scripts/python.exe)
Reticulate 1.34.0.9000 REPL -- A Python interpreter in R.
Enter 'exit' or 'quit' to exit the REPL and return to R.
>>> import pymc as pm
>>> 
>>> print(f"Running on PyMC v{pm.__version__}")
Running on PyMC v5.9.2
````

Reported first at https://github.com/quarto-dev/quarto-cli/issues/7684

**Comment by mike-duran-mitchell** [comment]
Any updates on this? pymc works in markdown, but not when knitting or jupyter notebooks for me.

**Comment by t-kalinowski** [comment]
Thanks, I can reproduce. 

The error is raised from pytensor. While loading, it inspects `sys.stdout.encoding`. 
https://github.com/pymc-devs/pytensor/blob/b63ee0cdaedb5f5e25199b2ccc5590b61e371e05/pytensor/link/c/cmodule.py#L2746

When kniting a document with the reticulate engine, [we replace `sys.stdout` with a `io.StringIO`](https://github.com/rstudio/reticulate/blob/0e5676e0f86d28a5d2a4f532debcb3568a59618d/inst/python/rpytools/output.py#L10) object to capture output. 

It seems `StringIO().encoding` returns `None`. This is an intentional choice - even though the  `StringIO()` subclasses `BytesIO()` and the underlying object is [hardcoded to have an encoding of `"utf-8"`](https://github.com/python/cpython/blob/648c44d3f7a020c7fed95d57b105738cf018a7cc/Lib/_pyio.py#L2646  ), `StringIO()` intentionally [makes sure that `encoding` return `None`](
https://github.com/python/cpython/blob/648c44d3f7a020c7fed95d57b105738cf018a7cc/Lib/_pyio.py#L2679C1-L2681C20), since it's meant to present as a native python string.

I think the most correct fix would be to update usage in https://github.com/pymc-devs/pytensor/blob/b63ee0cdaedb5f5e25199b2ccc5590b61e371e05/pytensor/link/c/cmodule.py#L2746 to use `sys.getdefaultencoding()`

**Comment by t-kalinowski** [comment]
@mike-duran-mitchell @cderv Thanks for reporting. I've opened a PR upstream with a fix.

In the mean time, you can workaround the bug by importing `pymc` the first time in a session outside of python code chunk, in a regular R chunk. For example:

````
---
title: "Test"
output: html_document
---

```{r, include = FALSE}
reticulate::py_run_string("import pymc as mc")
```

```{python}
import pymc as pm
```
````

**Comment by mike-duran-mitchell** [comment]
Thanks, I had started to dive into the code of pytensor and pymc and reticulate, so I am truly appreciative you were able to diagnose it so quickly. The solve using `reticulate::py_run_string("import pymc as mc")` at the top has worked like a charm so far. I was able to load in a large model using dill and inspect the results.
