### ISSUE TITLE
exception types not displayed in knitr markdown Rnw document

### ISSUE THREAD

**Issue by brry** [rstudio/reticulate#1520]
In Rnw Python chunks, exception types are no longer included in the output. 
In version 1.28, the example below showed
`## ValueError: invalid literal for int() with base 10: 'charstring'`
starting with version 1.29 ([lots of exception changes](https://github.com/rstudio/reticulate/releases/tag/v1.29)), it only shows
`## invalid literal for int() with base 10: 'charstring'`
without the `ValueError:` part.

Is this intentional?  
Can I get the exception types back? (I use it in slides for teaching Python, so they are really nice to have).

Note: I originally filed the issue in [knitr](https://github.com/yihui/knitr/issues/2316), but it belongs here.

Content of `ShowPyException.Rnw` file:
````
---
title: "ShowPyException"
output: beamer_presentation
---

## slide title

```{python, error=TRUE}
obj = "charstring"
int(obj)
```
````

**Comment by t-kalinowski** [comment]
Hi, thanks for reporting. This change was not intentional, and we'll certainly want to fix this before the next release. 

Would you like to submit a PR?

**Comment by brry** [comment]
I'd like to, but I don't know where to get started. If you could give me a pointer, I would love to try.

**Comment by t-kalinowski** [comment]
The work of parsing, evaluating, and processing output from python chunks happens in `eng_python()`. You may want to start by stepping through that function in an interactive R session, and note where the error is getting captured and printed. Then add a case that will construct the correct exception message from the captured exception object. 

The python code gets evaluated in a `tryCatch` (https://github.com/rstudio/reticulate/blob/efacf71d9e17c177424b72dc75349d8e346131f5/R/knitr-engine.R#L256), so that means we'll have access to the live python exception object, which we can use to construct the correct message, either directly in the engine (or maybe in `eng_python_autoprint`?), with something like `import("traceback")$format_exception(...)`, or via `reticulate::py_last_error()$message`.

**Comment by brry** [comment]
So far, I've tracked it down to `wrap` at the end of [eng_python](https://github.com/rstudio/reticulate/blob/main/R/knitr-engine.R#L383).
`outputs$data()` still has the error name, the result of `wrap` (knitr::engine_output) lost it. As far as I can tell, `outputs$data()[[2]]` is the `e` in the example above and `str(e)` also loses the name, hence I guess it never gets wrapped.
In case it is `knitr::engine_output` that needs fixing, I think line [82](https://github.com/yihui/knitr/blob/master/R/engine.R#L82) points at [sew](https://github.com/yihui/knitr/blob/master/R/output.R#L454) as the likely place.

I will keep investigating once I have some more time.
