### ISSUE TITLE
urllib does not know https when called from reticulate but does when called directly from python

### ISSUE THREAD

**Issue by raphywink** [rstudio/reticulate#177]
While trying to get the `keras` package to download the mnist dataset (`keras::dataset_mnist()`) on my Ubuntu 17.10 machine I stumbled over the following error:

```r
Error in py_call_impl(callable, dots$args, dots$keywords) : 
  Exception: URL fetch failure on https://s3.amazonaws.com/img-datasets/mnist.npz: None -- unknown url type: https

Detailed traceback: 
  File "/home/nameOfMyHomeDir/anaconda/envs/r-tensorflow/lib/python3.6/site-packages/keras/datasets/mnist.py", line 23, in load_data
    file_hash='8a61469f7ea1b51cbae51d4f78837e45')
  File "/home/nameOfMyHomeDir/anaconda/envs/r-tensorflow/lib/python3.6/site-packages/keras/utils/data_utils.py", line 224, in get_file
    raise Exception(error_msg.format(origin, e.errno, e.reason))
```

after a bit of digging I was able to narrow in on the problem:

```r
library(reticulate)
use_condaenv(condaenv = "r-tensorflow", conda = "/home/nameOfMyHomeDir/anaconda/bin/conda", required = T)
urllib <- import("urllib.request")
urllib$urlopen("https://s3.amazonaws.com/img-datasets/mnist.npz")
``` 
causes the same error. Funnily enough the following works in the anaconda r-tensorflow environment without a problem:

```python
import urllib.request
urllib.request.urlopen('https://s3.amazonaws.com/img-datasets/mnist.npz').read()
```
 Does reticulate somehow interfere with the openssl integration of the urllib module? Or am I just missing something completely obvious? Thanks in advance...

**Comment by jjallaire** [comment]
Reticulate does nothing to interfere with these calls. My guess is that somewhere in your shell environment variables there is an LD_LIBRARY_PATH (or other) variable set that makes it possible to use https but somehow those aren't in your R session. That's just my best guess, it's generally nearly impossible to remote speculate about these sorts of issues as they are typically idiosyncratic to a given system, configuration, environment, etc.

**Comment by raphywink** [comment]
Thanks for this. Will have a look through my environment variables when I am back on my Ubuntu machine (will report back if I find anything). Closing issue as this most likely has nothing to do with reticulate.

**Comment by stephansgit** [comment]
I had the same problem on Ubuntu 16.04.
I solved it as follows:

Turns out that `libcurl` has to be installed first (`sudo apt-get install libcurl4-openssl-dev
`), and _afterwards_ install `R` (see for instance [here)](https://cloud.r-project.org/) and `RStudio` (in case you want that).

**Comment by raphywink** [comment]
@stephansgit thanks for this! I actually got it to work under a different user on the same machine. However, yesterday I unistalled & reinstalled R under the user it didn't work for and voila it worked :-). So thank you!

**Comment by nwillems94** [comment]
For others having issues with this, the above worked for me with a caveat:

When I first ran `install_keras()` I got the standard "no module named keras" found error that seems to be quite common. It turns out keras itself was not actually installed to the conda env. I'm not sure why (maybe an issue with WSL or firewall in windows). 

So I first tried manually installing it by calling `conda install --name r-tensorflow keras` from the terminal.

**DON'T DO THIS.** I still had the same https errors as @raphywink where urllib worked in python but not in R

Instead, call `conda_install('r-tensorflow','keras')` from **inside R**. Not sure if it makes a difference but I also ran all these commands from R by calling `sudo R`

Apologies for those of you for which this is obvious blabber but it was a major headache from me. 

(I am running rstudio-server on Ubuntu 8.04 installed on WSL on Windows 10)
