### ISSUE TITLE
pd.read_csv  vs  pd$read_csv

### ISSUE THREAD

**Issue by jeonghyunwoo** [rstudio/reticulate#201]
I have a 9.57 MB file.
In jupyter notebook, following codes work: 
`df = pd.read_csv('df.csv')`
but in reticulate, error occurs
`df = pd$read_csv('df.csv')`   
`#Error: cannot allocate vector of size 141 kb`

**Comment by jjallaire** [comment]
Can you provide a link to the actual data file so we can attempt to reproduce this?

This is likely something related to how much actual memory is available within your R session.

**Comment by jeonghyunwoo** [comment]
sorry, actual data file is company inside  data, so sharing is prohibited.
any method for checking actual memory?

**Comment by fabianegli** [comment]
If you can not share the original file with which you encountered the issue, you should try to create a file with dummy data to reproduce the issue and share this file containing made-up data. In your case, some Korean words in the header and random values in the file should do just fine.

Alternatively, try to skip the header when reading the file. The `skiprows` argument of the [read_csv](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.read_csv.html) function will help with that. If you skip the header and it works, you could then later add the column names from a list manually or with a little bit of coding by reading the header separately. If it still does not work the issue is not related to the Korean-containing-header.

**Comment by fabianegli** [comment]
If you are working on a Windows machine, you can check the memory limit with `memory.limit()` and set it with `memory.limit(size=#yourrequiredmemorysize)`. 
You can try  memory limit ([https://stackoverflow.com/a/44042996](https://stackoverflow.com/a/44042996), [https://stackoverflow.com/a/32496590](https://stackoverflow.com/a/32496590)) and memory size [https://www.rdocumentation.org/packages/utils/versions/3.6.1/topics/memory.size](https://www.rdocumentation.org/packages/utils/versions/3.6.1/topics/memory.size) functions.
