### ISSUE TITLE
Sparse Matrix conversion fails under Python 2

### ISSUE THREAD

**Issue by jjallaire** [rstudio/reticulate#230]
This code fails for me when running with Python 2 (default version of Python installed with OS X, scipy installed within a virtual environment):

```r
library(reticulate)
library(Matrix)

N <- 1000
x <- sparseMatrix(
  i = sample(N, N),
  j = sample(N, N),
  x = runif(N),
  dims = c(N, N))
result <- r_to_py(x)
```

```
Error in py_call_impl(callable, dots$args, dots$keywords) : 
 TypeError: could not interpret data type 
6. stop(structure(list(message = "TypeError: could not interpret data type", 
    call = py_call_impl(callable, dots$args, dots$keywords), 
    cppstack = structure(list(file = "", line = -1L, stack = c("1   reticulate.so                       0x000000010f635fc4 _ZN4Rcpp9exceptionC2EPKcb + 276", 
    "2   reticulate.so                       0x000000010f635df0 _ZN4Rcpp4stopERKNSt3__112basic_stringIcNS0_11char_traitsIcEENS0_9allocatorIcEEEE + 48",  ... 
5. getdtype at sputils.py#101
4. __init__ at compressed.py#52
3. sp$csc_matrix(tuple(x@x, x@i, x@p), shape = dim(x)) at conversion.R#349
2. r_to_py.dgCMatrix(x) at conversion.R#12
1. r_to_py(x) 
```

@terrytangyuan I am hoping to do a reticulate release in a week or so. Could you take a look at this one?

**Comment by terrytangyuan** [comment]
Thanks. The problem is that older version of scipy could not infer the data types automatically. The scipy installed within virtual environment is super old:
```
> import("scipy")[["__version__"]]
[1] "0.13.0b1"
```

The one I was using under both py2 and py3 in conda works fine with scipy version `1.0.0`. Could you try upgrade and let me know if it works for you? 

One workaround would be supplying `dtype = np$float64` to `csc_matrix()`. However, it's hard to determine the underlying dtype automatically and I am not sure if it's a good idea to support such old version of scipy.

**Comment by jjallaire** [comment]
Okay, I was using the scipy that ships with OS X. Doing a simple `virtualenv_install()` of SciPy resolved the issue.
