### ISSUE TITLE
Cannot use name 'pop' in Pandas DataFrame

### ISSUE THREAD

**Issue by ijlyttle** [rstudio/reticulate#244]
This may be related to #157 

```r
library("reticulate")

py_run_string("import pandas as pd")
py_run_string("df_bad = pd.DataFrame({'pop': ['foo']})")
py_run_string("df_good = pd.DataFrame({'apop': ['foo']})")
```

So far so good, but when I try to bring this into R:

```r
py$df_bad
```

```
Error in py_get_attr_impl(x, name, silent) : 
  AttributeError: 'function' object has no attribute 'as_matrix'
```

However:

```r
py$df_good
```

```
  apop
1  foo
```

It seems like the name `'pop'` is somehow messing things up, and I don't think it should.

**Comment by AliciaSchep** [comment]
In python, doing 

```py 
df_bad.pop.as_matrix()
``` 

gives an error.  This is because `pop` is a method of a DataFrame.  

The following in python works:

```py
df_bad[['pop']].as_matrix()
```
It seems like somewhere in reticulate's conversion df_bad.pop.as_matrix is getting called and if that could be avoided by calling df_bad[['pop']].as_matrix that would solve the issue... there are likely other DataFrame methods other than pop that will lead to this kind of unexpected error.

**Comment by ijlyttle** [comment]
Nice catch, thanks!

**Comment by jjallaire** [comment]
Assuming we can now close this?

**Comment by ijlyttle** [comment]
Yes, thanks!
