### ISSUE TITLE
Set up path to python in R package using `use_python()`

### ISSUE THREAD

**Issue by hadinh1306** [rstudio/reticulate#286]
I'm writing a R package that uses my python code source file. I wonder how I should deal with setting up the path to python using `use_python()`, so other teammates can also run the package?

**Comment by jjallaire** [comment]
This article covers using reticulate in a package: https://rstudio.github.io/reticulate/articles/package.html

To address your specific question, package never call `use_python` (that's for end users). When reticulate attempts to resolve your call to `import()` it will actually search the users system for a Python version/environment which contains the package you are importing. If this doesn't yield a correct or otherwise desirable version of Python then users can invoke `use_python()` manually.

**Comment by sumedhkumarprasad** [comment]
![python_path_setting_in_R](https://user-images.githubusercontent.com/29379271/55384661-e638d000-5548-11e9-8788-211329ac0f0c.PNG)

**Comment by dfalbel** [comment]
We have significantly refactored Python discovery rules in reticulate v1.31. Please refer this [article](https://rstudio.github.io/reticulate/articles/versions.html#order-of-discovery) for more information and open a new issue if the problem still happens.
