### ISSUE TITLE
Updating pyc-files

### ISSUE THREAD

**Issue by mikldk** [rstudio/reticulate#302]
Hello,

Thank you for this nice package!

I am currently using `reticulate` in a package and have included two Python scripts in the package's `inst/python` directory.

I have a question about making the development cycle easier: So when I start the R session and do a `devtools::load_all(".")`, then `pyc` files are compiled. When I then change something in the `py` source files and do a `devtools::load_all(".")`, the `pyc` files are not updated. I get that this is probably expensive and not easy. But currently it seems like I have to restart the entire R session to force a recompilation of the `py` files to `pyc` files. I am looking for something less painful than having to restart the entire R session: Can I somehow trigger this `py` to `pyc` compilation and reload without restarting the entire R session?

Cheers,
Mikkel.

**Comment by jjallaire** [comment]
The problem is that devtools doesn't know about sourced python files. It looks to me from the documentation of `load_all` that if you sourced the Python code in your package `.onLoad` or `onAttach` event then it would get re-run: https://www.rdocumentation.org/packages/devtools/versions/1.13.5/topics/load_all

There is a major cautionary note here though: As described here in the docs on delay loading of Python (https://rstudio.github.io/reticulate/articles/package.html) reticulate code in a package really should not be initializing Python when the package loads (this is because it eliminates the possibility of the user calling e.g. `use_python()` or `use_virtualenv()` after your packages `library()` call. What you should probably do is this:

1) Source the Python code on-demand when your package needs it; and

2) In `.onLoad` or `.onAttach`, only re-source the Python code if Python is already initialized (e.g. `reticulate::py_available()`

**Comment by mikldk** [comment]
Thank you for the very useful answer!

It seems like a `reticulate::source_python("inst/python/file.py")` will be useful in the development cycle.

I do something like this to mimic the behaviour in `.onLoad` where a global variable e.g. `mod` is assigned by `reticulate::import_from_path()`:

```
mod_env <- new.env()
reticulate::source_python("inst/python/file.py", envir = mod_env)
mod <- get("ModuleName", envir = mod_env)
```

This means that I get the module in a variable instead of just as objects in the global environment.
