### ISSUE TITLE
Import local module fails in REPL (repl_python())

### ISSUE THREAD

**Issue by gsimchoni** [rstudio/reticulate#340]
Simple reproducible example:

Under C directory I have "utils" directory with `__init__.py` file and `utils.py` file:

C\:
*utils
**`__init__.py`
**`utils.py`

In Python this should be enough for "utils" to be a "package", and for `from utils import *` to work in REPL, say IDLE:

![image](https://user-images.githubusercontent.com/9554580/44324112-369d6a80-a45d-11e8-8849-7bd75d8e0d40.png)

This doesn't work in `reticulate::repl_python()`:

![image](https://user-images.githubusercontent.com/9554580/44324206-9562e400-a45d-11e8-8ca2-730392d8e213.png)

Am I doing something wrong, is it a bug or not yet a feature?

Rstudio v1.2.830

```
> sessionInfo()
R version 3.5.1 (2018-07-02)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=English_Israel.1252  LC_CTYPE=English_Israel.1252    LC_MONETARY=English_Israel.1252
[4] LC_NUMERIC=C                    LC_TIME=English_Israel.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] reticulate_1.10

loaded via a namespace (and not attached):
[1] compiler_3.5.1  Matrix_1.2-14   tools_3.5.1     Rcpp_0.12.18    grid_3.5.1      jsonlite_1.5   
[7] png_0.1-7       lattice_0.20-35
```

**Comment by kevinushey** [comment]
This appears to be because, when Python is launched within a terminal, an empty path entry is added to `sys.path`. E.g. in IDLE:

<img width="688" alt="screen shot 2018-08-22 at 4 46 33 pm" src="https://user-images.githubusercontent.com/1976582/44496816-13c0b100-a62b-11e8-80e3-bb84df829ea2.png">

And in RStudio:

<img width="639" alt="screen shot 2018-08-22 at 4 47 21 pm" src="https://user-images.githubusercontent.com/1976582/44496818-1a4f2880-a62b-11e8-94fd-0b9046795503.png">

I'll fix this up. Thanks for reporting!

**Comment by cboettig** [comment]
@kevinushey was this resolved?  I continue to get this error in RStudio / repl_python() from any python script that tries to `import` to refer to files in the working directory.

**Comment by t-kalinowski** [comment]
I think this is resolved. `sys.path[0]` returns an empty string, which means that the current directory is looked in by python for modules. If you're still seeing this, can you please open a new issue?

**Comment by cboettig** [comment]
@t-kalinowski okay cool, I'll open a new issue.  (briefly I am still seeing this, I do see the empty string, the empty string does not seem to mean "current working directory" though.  if I do `sys.path.insert(0, ".")`, i.e. using `.` instead of an empty string, my code works as expected when run with `repl_python()`)
