### ISSUE TITLE
Reticulate fails for python (pyspark) scripts which has spark session initiation 

### ISSUE THREAD

**Issue by ashishmenkudale** [rstudio/reticulate#377]
Objective: Working in azure HDInsight environment, make further pipeline work.  1. use python (pyspark) for data ETL, read/write and preapre dataframe. 2. use R for algorithm on this dataframe. 3. pass results to python(pyspark) script for writing ops.
python scripts something similar to--

```
#####
#python_read.py
from pyspark.sql import SparkSession
from pyspark.sql import SQLContext
from pyspark.sql import HiveContext

#import os
#os.environ['PYSPARK_PYTHON'] = "/usr/bin/anaconda/envs/py35/bin/python"
#os.environ['SPARK_CLASSPATH'] = "/path/to/mssql-jdbc-6.2.2.jre8.jar"
spark = SparkSession.builder.appName("some_app").enableHiveSupport().getOrCreate()
df_rdd = spark.read("SELECT * FROM DB.TABLE")
#####
```

In R, something similar to--
```
#####
#algorithm.R
reticulate::use_python("/usr/bin/anaconda/envs/py35/bin/python")
reticulate::py_run_file("~/python_read.py")
#get df_rdd and do calculations
######
```

This strategy fails @ py_run_file("~/python_read.py") "could not find pyspark module". 

I have checked that, in console,  
>/usr/bin/anaconda/envs/py35/bin/python ~/python_read.py

works perfectly and I get df_rdd. I am not sure about all dependencies required for reticulate to initiate the pysaprk sesion. Also, if this is pysparkissue, or R issue.
Can you please help? 

Thanks.

**Comment by jjallaire** [comment]
The problem is almost certainly that the environment variables required to load PySpark are not set correctly with the R session (I see references to PYSPARK_PYTHON and SPARK_CLASSPATH above, are those both available in the R session). 

In any case, this isn't an issue w/ reticulate, it's an issue with priming the R session correctly to load pyspark. Since you are running in HDInsight, you'll need to work with Microsoft on sorting out what environment variables need to be set and where this should occur in your configuration.
