### ISSUE TITLE
Potential unstable detection of Python modules

### ISSUE THREAD

**Issue by terrytangyuan** [rstudio/reticulate#51]
I am having a weird problem in RStudio where sometimes it cannot find a particular module in a Python package, for example:

```
 Error in py_module_import(module, convert = convert) : 
  ImportError: No module named tensorflow.contrib.learn 
```

```
 Error in py_module_import(module, convert = convert) : 
  ImportError: No module named tensorflow.python.ops.random_ops 
```

This error seems random. I had to re-open RStudio 3 or more times and finally it will find all the modules correctly. 

Is there any potential piece of code that would cause this instability?

Note that the Python modules can be find via python on console and this problem only appears in RStudio (Rscript runs fine).

**Comment by jjallaire** [comment]
I know what the problem is -- you are using another python module before
the delay_load of tflearn kicks in.

I had the same problem in keras and developed a workaround, however I
realize now that reticulate should give priority to the very first module
registered with delay_load (rather than "last one wins").

Net: this should be fixed in reticulate. Try again and let me know if you
continue to have problems.

**Comment by terrytangyuan** [comment]
This works! Thanks for the quick fix!

**Comment by MAAbdullah47** [comment]
Hi Guys
I have the same problem, can anyone help me how to use reticulate to solve the problem of tensorflow?

**Comment by eddelbuettel** [comment]
There is extensive documentation at the [Tensorflow for R](https://tensorflow.rstudio.com/) site about how to get started, and reticulate is at the very core of it.

**Comment by StatXue** [comment]
i have the same issue~~
