### ISSUE TITLE
priority in delayed onload

### ISSUE THREAD

**Issue by sebastiangonsal** [rstudio/reticulate#533]
What exactly does the priority argument on .onload signify? Tensorflow r package sets it to 5. Is that a magic number ?

**Comment by jjallaire** [comment]
If 2 packages both import Python packages in their .onload statement, the
import with the higher priority will be used to determine which has
priority in the search for a version of Python that can satisfy the import.
That was put in specifically for this scenario:

library(tensorflow)
library(keras)

Where keras needed to have higher priority (otherwise we might find a
version of Python that has tensorflow but not keras).

**Comment by sebastiangonsal** [comment]
Makes sense. I was just confused on why the priority is 5 and not 2. But i guess thats arbitrary.

**Comment by sebastiangonsal** [comment]
@jjallaire can i ask another thing on the tensorflow package. What do these lines do:
```
# globals
.globals <- new.env(parent = emptyenv())
.globals$tensorboard <- NULL
```

The `.globals` environment is defined but not used anywhere. How is `.globals` used in this package?

**Comment by skeydan** [comment]
it is:

```
R/package.R:# globals
R/package.R:.globals <- new.env(parent = emptyenv())
R/package.R:.globals$tensorboard <- NULL
R/tensorboard.R:  if (!is.null(.globals$tensorboard)) {
R/tensorboard.R:    p <- .globals$tensorboard$process
R/tensorboard.R:      port <- .globals$tensorboard$port
R/tensorboard.R:    .globals$tensorboard <- NULL
R/tensorboard.R:    .globals$tensorboard <- list(process = p, port = port)
R/extract.R:  .globals$builtin_ellipsis %||%
R/extract.R:  (.globals$builtin_ellipsis <- import_builtins(FALSE)$Ellipsis)
R/extract.R:  slice <- .globals$py_slice
R/extract.R:    .globals$py_slice <- slice <- import_builtins(FALSE)$slice
```
