### ISSUE TITLE
python lists of size 1 are translated to non-lists

### ISSUE THREAD

**Issue by ucpresearch** [rstudio/reticulate#574]
First, thanks for writing the package. I found an inconsistency in the translation of python lists to R lists, as the following code demonstrates:
```
library(reticulate)
py <- import_builtins()
pyid <- py_eval("lambda x: x")
sapply(lapply(list(list("a"), list("b", "c"), list()), pyid), py$type)
```

Which returns the following:
```
[[1]]
<class 'str'>

[[2]]
<class 'list'>

[[3]]
<class 'list'>
```

In other words, lists of size other than one are returned (as they should) as lists, but lists of size 1 are demoted to their first item. Since python is explicitly returning a list, R should get a list back. 

Thanks,
- ucp

**Comment by ucpresearch** [comment]
My temporary / permanent solution (in case it's impossible to solve this issue due to existing code) is to use the following:
```
sapply(lapply(lapply(list(list("a"), list("b", "c"), list()), pyid), as.list), py$type)
```

**Comment by kevinushey** [comment]
I think this touches at a bit of the tension we have in converting objects between R and Python. Because R does not have true scalars -- e.g. `1` is really just a numeric vector of length one -- we had to make some decisions + tradeoffs when converting objects between Python and R.

For example:

``` r
library(reticulate)

a <- py_eval("'a'", convert = FALSE)
py_to_r(a)
#> [1] "a"

alist <- py_eval("['a']", convert = FALSE)
py_to_r(alist)
#> [1] "a"

r_to_py("a")
#> a
r_to_py(list("a"))
#> ['a']
```

<sup>Created on 2019-08-07 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Perhaps the safest thing would've been to always convert Python lists into R lists, but we found more often users wanted the automatic conversion from Python lists-of-identically-typed-objects to the R vector equivalent.

In a world where we always required NumPy for conversions (so that R vectors converted to their NumPy analogs, and vice versa) it might have been simpler to say "R lists are always converted to Python lists, and vice versa" but ultimately we didn't make that decision -- especially since many Python APIs expect plain Python lists rather than NumPy arrays.

**Comment by ucpresearch** [comment]
Yeah, I realized that this could be an issue. Thanks for the feedback though! I'll find a different way around this.
