### ISSUE TITLE
R S3 class incorrect for non converting iterator

### ISSUE THREAD

**Issue by t-kalinowski** [rstudio/reticulate#603]
``` r
library(tensorflow)
library(reticulate)

ds <- tf$data$Dataset$from_tensor_slices(1:10)

class(as_iterator(ds))
#> [1] "python.builtin.iterator"                                     
#> [2] "tensorflow.python.data.ops.iterator_ops.IteratorV2"          
#> [3] "tensorflow.python.training.tracking.base.Trackable"          
#> [4] "tensorflow.python.framework.composite_tensor.CompositeTensor"
#> [5] "python.builtin.object"

class(as_iterator(r_to_py(ds)))
#> [1] "tensorflow.python.data.ops.iterator_ops.IteratorV2"          
#> [2] "tensorflow.python.training.tracking.base.Trackable"          
#> [3] "tensorflow.python.framework.composite_tensor.CompositeTensor"
#> [4] "python.builtin.object"
```
Notice that `"python.builtin.iterator"` is missing for the second case. I ran into this because this subsequently causes `iter_next()` to fail the input check (though if I disable the check, the underlying implementation `py_iter_next()` still works.) 

<sup>Created on 2019-10-04 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by kevinushey** [comment]
This is because the convert flag is off in the Python object, and with that flag off we don't add our own custom classes. E.g.

https://github.com/rstudio/reticulate/blob/80423d6fdf43e91136cfff61a01a9c106b48a555/R/python.R#L1248

That bit of code is skipped in the second example.

That said, perhaps `iter_next()` could just check and see if the object has an `__iter__` attribute, rather than checking for our amended class.

**Comment by t-kalinowski** [comment]
having `iter_next` check for `__iter__`() feels like the right solution.

**Comment by t-kalinowski** [comment]
Thanks!
