### ISSUE TITLE
user is prompted for miniconda even if anaconda already present

### ISSUE THREAD

**Issue by cderv** [rstudio/reticulate#607]
It may be by design but I was surprised by this behavior, so I share it

I already have Anaconda installed, and it is found by reticulate, but now I am prompted about miniconda

```r
> library(reticulate)
> py_config()
No non-system installation of Python could be found.
Would you like to download and install Miniconda?
Miniconda is an open source environment management system for Python.
See https://docs.conda.io/en/latest/miniconda.html for more details.

Would you like to install Miniconda? [Y/n]: n
Installation aborted.
python:         C:\Users\chris\Anaconda3\envs\r-reticulate\python.exe
libpython:      C:/Users/chris/Anaconda3/envs/r-reticulate/python37.dll
pythonhome:     C:\Users\chris\Anaconda3\envs\r-reticulate
version:        3.7.3 | packaged by conda-forge | (default, Jul  1 2019, 22:01:29) [MSC v.1900 64 bit (AMD64)]
Architecture:   64bit
numpy:           [NOT FOUND]

python versions found: 
 C:\Users\chris\Anaconda3\envs\r-reticulate\python.exe
 C:\Users\chris\Anaconda3\python.exe
 C:\Users\chris\Anaconda3\envs\docker\python.exe
```

I would have expected reticulate to find my anaconda installation, and, possibly suggest to switch to miniconda if better. I find it odd to offer to download an other distribution whereas I have one working.

**Comment by kevinushey** [comment]
This was by design (although perhaps we can still reconsider). Our intention was that, unless the user has explicitly requested a particular version of Python with one of the `use_*()` helpers, we should prompt the user to install Miniconda and make that the default.

Note that you will only be prompted once, and rejecting that prompt is "sticky" (you won't get bugged about it again on the same account / machine)

**Comment by cderv** [comment]
I see. Thanks for the clarification ! I guess I should always use `use_*` to get going. And the message indeed appears only once. 

I guess it just feels unexpected when you already have anaconda configured to get advice to download the little brother miniconda. I would have considered to be prompted if no  Python was found or if on windows not a python with conda. 
But maybe there is a change in reticulate to consider that it should work better and exclusively with miniconda and it means I should switch  from Anaconda to miniconda ?

**Comment by jjallaire** [comment]
Our idea is that by standardizing on a known variant of Python we'll make
the package (and other packages that use it) easier to install and support.
As you may have noticed a large percentage of the GitHub issues are Python
configuration issues (often it's the case that the version the user already
has is somehow mal-configured)

**Comment by cderv** [comment]
That is completly understandable. This is the approach with TinyTex distribution too, that saves a lot of painful problem with Rmarkdown pdf rendering, regarding LaTex configuration. 

This is fine by me as when you say no it is not promped again. I'll document internally to our users to use miniconda with reticulate, also specify explicitly the python version. 

Thanks a lot for your precision.

**Comment by kevinushey** [comment]
I've now made this change: if an Anaconda environment is available, it will be used in preference to Miniconda.

**Comment by liuyigh** [comment]
> This was by design (although perhaps we can still reconsider). Our intention was that, unless the user has explicitly requested a particular version of Python with one of the `use_*()` helpers, we should prompt the user to install Miniconda and make that the default.
> 
> Note that you will only be prompted once, and rejecting that prompt is "sticky" (you won't get bugged about it again on the same account / machine)

And what can I do to get that prompt again now that I changed my mind? Thanks!

**Comment by kevinushey** [comment]
The response is stored in a file located at the path referenced by:

```
reticulate:::miniconda_meta_path()
```

If you remove that file, then `reticulate` will prompt again.

**Comment by tmichniewski** [comment]
Hello Kevin @kevinushey
Referring to
"This was by design (although perhaps we can still reconsider). Our intention was that, unless the user has explicitly requested a particular version of Python with one of the use_*() helpers, we should prompt the user to install Miniconda and make that the default."
This is perfectly fine if you use it just in R, where if propmted for installing Miniconda you can simply answer yes and that's it.
The other story is when you use it from let say Scala through RScala library, when you only need to use pyarrow to load parquet files. Then RClient of Rscala library is prompted with the question whether to install Miniconda, but the user of RScala API is not able to respond to this question, because it is visible only in the logs on the Azure Databricks cluster.
Having said this mybe you could reconsider this design decision.

**Comment by talesfc** [comment]
Happens to me just by loading a python script file. 
And won´t take no for answer:
would you like to install miniconda? [y/n]: n

**Comment by genobobeno** [comment]
I'm on a macbook with Big Sur, and I'm brand new to integrating python into my work. For my current project, I'm trying to build a neural network to compare with gbm, rf, glm, and an ensemble... and the python configuration is confusing because the documentation is missing any reference to the workarounds for all of the errors and warnings that RStudio over-engineered into their python-R integration. These warnings and error messages in the R console are very confusing: So far, the tensorflow package installed just fine, but the call `library(tensorflow)` returned a message that it couldn't load the tensorflow package because the tensorflow module isn't already installed in the python environment (nothing in the documentation says anything about this)... 
    
`Error: package or namespace load failed for ‘tensorflow’:
 .onLoad failed in loadNamespace() for 'tensorflow', details:
  call: py_module_import(module, convert = convert)
  error: ModuleNotFoundError: No module named 'tensorflow'`

and then the "install_tensorflow()" command prompts you to install a whole new miniconda installation (again, nothing in the webpage for tensorflow install says anything about this). And I just installed the python module to be able to load the tensorflow package, it now seems that running `install_tensorflow()` is redundant, and since there are multiple installations of python, I don't even know into which environment R is installing the dependencies and newer tensorflow module. I had very similar problems making all of this work on Windows 10 last Fall (2020), so the fact that this documentation still isn't noting these repeatable hiccups is disappointing.

So next, install_tensorflow() seemed to look up a hundred packages that have conflicts with everything in the base 'r-reticulate' environment. Literally everything says there's a conflict. I have no idea what to do about this. I'm not a python expert... I'm just trying to use R to run tensorflow. Here is just one sample of the 3000 lines of illegible output:

`Package libev conflicts for:
libnghttp2 -> libev[version='>=4.11|>=4.33,<4.34.0a0']
libcurl -> libnghttp2[version='>=1.41.0,<2.0a0'] -> libev[version='>=4.11|>=4.33,<4.34.0a0']
libev`

And to top it all off, install_tensorflow() seems to have tried to install python 3.7 into my 'r-reticulate' environment, which makes no sense to me at all... and nowhere in the documentation am I reading that R's tensorflow installation requires python 3.7. 

`Error: installation of 'python=3.7' into environment '/Users/eugene/opt/anaconda3/envs/r-reticulate' failed [error code 1]`

So now that this neophyte python user just installed a whole bunch of python crap that was essentially the "wrong version" and named an environment 'r-reticulate' to match RStudio's defaults, there is nowhere in the documentation that teaches you how to "back out" of everything that was just installed, so that I can go back and install anaconda3 under a different python version in the hopes that tensorflow will install again.

To say this is incredibly frustrating is an immense understatement.
