### ISSUE TITLE
Importing keras fails due to sys.stderr.write in __init__py

### ISSUE THREAD

**Issue by MichaelHeldmann** [rstudio/reticulate#65]
Trying to import the keras library fails supposedly because it contains a call to sys.stderr.write in __init__.py

keras <- import( "keras" )
Error in py_module_import(module, convert = convert) : 
  AttributeError: 'NoneType' object has no attribute 'write'

Detailed traceback: 
  File "C:\Users\MHELDM~1\AppData\Local\conda\conda\envs\tf\lib\site-packages\keras\__init__.py", line 3, in <module>
    from . import activations
  File "C:\Users\MHELDM~1\AppData\Local\conda\conda\envs\tf\lib\site-packages\keras\activations.py", line 4, in <module>
    from . import backend as K
  File "C:\Users\MHELDM~1\AppData\Local\conda\conda\envs\tf\lib\site-packages\keras\backend\__init__.py", line 72, in <module>
    sys.stderr.write('Using TensorFlow backend.\n')

commenting out the call to sys.stderr.write in __init__.py solves the problem. Might there be an issue with how sys.stdout and sys.stderr is dealt with in the initialization phase of a python module?

**Comment by jjallaire** [comment]
The problem here is that in some configurations `sys.stdout` and `sys.stderr` are actually NULL. I just pushed a fix to reticulate yesterday that addresses this. You can install it as follows:

```r
devtools::install_github("rstudio/reticulate")
```

That said, if you want to use keras I strongly recommend you check out the keras package (which uses reticulate to provide a more native R interface to keras): https://rstudio.github.io/keras/
