### ISSUE TITLE
How to deal with infinite iterators / generators ?

### ISSUE THREAD

**Issue by nakamichiworks** [rstudio/reticulate#68]
Some Python functions return infinite iterators / generators ( `keras::flow_images_from_data()`, for example).
For such iterators / generators, `reticulate::iterate()` gets into an infinite loop, and it cannot be used in R's `for` loops as in native Python's `for` loops.

An obvious solution to the problem is to use Python's built-in `next()` function, but it seems a bit awkward because `next` is a keyword in R and you must quote it to call from R.

Do you have any better idea for the problem ?

```r
library(reticulate)

py <- import_builtins()

# create an infinite generator
main <- py_run_string("
def foo():
    n = 0
    while True:
        yield n
        n += 1
")
it <- main$foo()

# This gets into an infinite loop
for(i in iterate(it)) {
  print(i)
  if(i >= 10) break
}

# It works, but seems a bit awkward
while(TRUE) {
  i <- py$`next`(it)
  print(i)
  if(i >= 10) break
}

```

**Comment by terrytangyuan** [comment]
Thanks for the report! This is indeed something we are missing. I imagine we can add an S3 method `next()` that works on iterator/generator objects. @jjallaire Do you see any potential problems?

**Comment by jjallaire** [comment]
Good catch! Just added an `iter_next` function for this. Docs are here: https://rstudio.github.io/reticulate/articles/introduction.html#element-level-iteration

**Comment by nakamichiworks** [comment]
Thank you for a very quick fix !

**Comment by jjallaire** [comment]
Note that the default completed value for `iter_next` has just changed from `NA` to `NULL` (although you can always use the `completed` parameter to change this). Here are the update docs: https://rstudio.github.io/reticulate/articles/introduction.html#iterators

If you want to write code that works correctly with both the current version of reticulate on CRAN and the next version (master) just explicitly specify `completed = NA` rather than relying on the default.

Note that this change was made as part of adding support for creating generators (Python iterators implemented as R functions). Docs on generators are here: https://rstudio.github.io/reticulate/articles/introduction.html#generators
