### ISSUE TITLE
Disable prompt to install miniconda

### ISSUE THREAD

**Issue by jgbradley1** [rstudio/reticulate#710]
When reticulate uses the default python executable on `PATH` or via the `RETICULATE_PYTHON` environment variable, it still prompts to install Miniconda. When I say "no", it will still work. How can the prompt be disabled?

```
> library(reticulate)
> os <- import("os")
No non-system installation of Python could be found.
Would you like to download and install Miniconda?
Miniconda is an open source environment management system for Python.
See https://docs.conda.io/en/latest/miniconda.html for more details.

Would you like to install Miniconda? [Y/n]: n
Installation aborted.
> os$listdir() # this is a successful call
```

My specific case - I'm trying to knit RMarkdown documents that use reticulate. In non-interactive R sessions (which occurs when knitting RMarkdown docs from the command line), I would expect reticulate to still work and not hang on the prompt.

**Comment by kevinushey** [comment]
Can you provide a reproducible example? I'm surprised because this shouldn't be the case -- if `RETICULATE_PYTHON` is set, then the Miniconda-related logic should be bypassed.

The miniconda check happens here:

https://github.com/rstudio/reticulate/blob/9dedfb3fa043ed5f035d6a1ee162cc9ee3b1c64e/R/config.R#L169-L202

and you'll see the various other checks (e.g. with `RETICULATE_PYTHON`) happen above.

**Comment by StephenElston** [comment]
Hi. I have the same issue. In my case, the R console just hangs, regardless if I answer 'Y' or 'n'. I don't need miniconda since I have full conda installed and working just fine. 

The question asking if I want to install miniconda can take some time to appear on startup. Once it does, the console, and sometimes all of RStudio, hangs. Is there a way to disable this behavior? 

For the record, I am creating RMarkdown documents using Python and full Anaconda. I cannot tell if kniting does or does not cause the hang, but this may be the case. The behavior is the same regardless of which .rmd file containing Python I use, so I don't think there is anything specific to the contents of my files.  All of the files start with the same script shown here: 

```
---
title: "Some plots with Python"
author: "me"
date: "April 14, 2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(reticulate)
use_python("/usr/bin/python3")
matplotlib <- import("matplotlib")
matplotlib$use("Agg", force = TRUE)
```


For the record, on startup I see the following in my console:


```
R version 3.6.3 (2020-02-29) -- "Holding the Windsock"
Copyright (C) 2020 The R Foundation for Statistical Computing
Platform: x86_64-w64-mingw32/x64 (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

[Workspace loaded from ~/.RData]

Loading required package: RPostgreSQL
Loading required package: DBI
Would you like to install Miniconda? [Y/n]: n

```

That's it. The console is hung!

**Comment by cderv** [comment]
I opened a similar issue a while back https://github.com/rstudio/reticulate/issues/608
Setting 
```
RETICULATE_MINICONDA_ENABLED=FALSE
```
as environment variable will deactivate the check for miniconda and the prompt.

**Comment by aloboa** [comment]
I think I have the same problem (see below), where should I set that environment variable? in the console or within the R session?

Fresh RStudio session:

```
> require(reticulate)
Loading required package: reticulate
> py_discover_config()
No non-system installation of Python could be found.
Would you like to download and install Miniconda?
Miniconda is an open source environment management system for Python.
See https://docs.conda.io/en/latest/miniconda.html for more details.

Would you like to install Miniconda? [Y/n]: n
Installation aborted.
python:         /usr/bin/python3
libpython:      /usr/lib/python3.9/config-3.9-x86_64-linux-gnu/libpython3.9.so
pythonhome:     //usr://usr
version:        3.9.5 (default, Nov 18 2021, 16:00:48)  [GCC 10.3.0]
numpy:          /home/alobo/.local/lib/python3.9/site-packages/numpy
numpy_version:  1.20.3

python versions found: 
 /usr/bin/python3
 /home/alobo/miniconda3/bin/python
 /home/alobo/miniconda3/envs/qgis_stable/bin/python
```

Instead, the "raw R" session (without RStudio, does not complain:

```
> require(reticulate)
Loading required package: reticulate
> py_discover_config()
python:         /usr/bin/python3
libpython:      /usr/lib/python3.9/config-3.9-x86_64-linux-gnu/libpython3.9.so
pythonhome:     //usr://usr
version:        3.9.5 (default, Nov 18 2021, 16:00:48)  [GCC 10.3.0]
numpy:          /home/alobo/.local/lib/python3.9/site-packages/numpy
numpy_version:  1.20.3

python versions found: 
 /usr/bin/python3
 /home/alobo/miniconda3/bin/python
 /home/alobo/miniconda3/envs/qgis_stable/bin/python
```

Console:

```
$ which python
/home/alobo/miniconda3/bin/python
$ which python3
/home/alobo/miniconda3/bin/python3

```

**Comment by t-kalinowski** [comment]
What is the result of `Sys.which("python")` from within RStudio?

You can set the environment variable by writing it to a .Renviron file, or calling `Sys.setenv()` in an R session (before reticulate is loaded)

**Comment by aloboa** [comment]
Sys.setenv(RETICULATE_MINICONDA_ENABLED=FALSE)
does the trick.
Should this not be mentioned in the documentation?

**Comment by AbdurrahmanMN** [comment]
Rstudio failed to start for a week now.

Until today, I removed startup .Rprofile, .Renviron, and .RData from my working directory as recommended here:
https://support.posit.co/hc/en-us/articles/200488508-RStudio-Desktop-IDE-Will-Not-Start

It finally worked, but this appeared on R console upon start up:
`R version 4.2.2 (2022-10-31 ucrt) -- "Innocent and Trusting"
Copyright (C) 2022 The R Foundation for Statistical Computing
Platform: x86_64-w64-mingw32/x64 (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

**Error in conda_python(envpath, conda = miniconda) : 
  no conda environment exists at path 'C:/Users/Name/AppData/Local/r-miniconda/envs/r-reticulate'
Calls: do.call -> <Anonymous> -> <Anonymous> -> conda_python
Execution halted**`

Note that:
`Sys.which("python")`
gives
` python 
"C:\\Users\\Name\\AppData\\Local\\Programs\\Python\\PYTHON~1\\python.exe" `

and I tried 
`Sys.setenv(RETICULATE_MINICONDA_ENABLED=FALSE)` but it didn't work

**Comment by daattali** [comment]
I'm also running into the issue of the "Would you like to download and install Miniconda?" prompt appearing and disturbing.

In my usecase, it actually happens when I try to restart the RStudio session. I'm not a python user so it's difficult for me to trace down where/why/when exactly the issue happens, but I'm able to reproduce it using a package that uses reticulate in a very basic way https://github.com/dominodatalab/DominoDataR 

```r
> client <- DominoDataR::datasource_client()

# now I can run as many commands as I want without any issue

# restart the RStudio server via the menu or crl+shift+f10
Restarting R session...

No non-system installation of Python could be found.
Would you like to download and install Miniconda?
Miniconda is an open source environment management system for Python.
See https://docs.conda.io/en/latest/miniconda.html for more details.

Would you like to install Miniconda? [Y/n]: 
```

This seems to happen only when I save the result of the function call to a variable. I'm able to interact with reticulate and do everything I need, yet I get this prompt at the end of my session.

Figuring out why it's happening would be great, but it would also be useful to simply allow us a way to explicitly suppress this prompt.

**Comment by cderv** [comment]
@daattali see https://github.com/rstudio/reticulate/issues/710#issuecomment-651121592 above

I understand from your post that setting the environment variable does not work for you ?

**Comment by daattali** [comment]
@cderv I did try setting that envvar and I still got that prompt.
Perhaps the "restart" does work, which resets the envvars, and that prompt happens after the envvar is already cleared.

**Comment by t-kalinowski** [comment]
If you respond "no" to the install miniconda prompt, that response is saved by reticulate and you shouldn't be prompted again.

**Comment by daattali** [comment]
That's true, and I can do that myself when I write code for my own use. But that's problematic when I'm building software for others to use, and they don't understand what this message is and pressing "Esc" or ctrl+c doesn't do anything.

**Comment by daattali** [comment]
I just verified that `RETICULATE_MINICONDA_ENABLED=FALSE` does indeed work, but in my case that's only a theoretical solution, not a practical one. Because I'm getting the prompt **at the start of an R session**, the only way to disable it is to set the envvar at the system level rather than at the session level. I don't think it's reasonable to ask users to add that envvar to their system.

**Comment by cderv** [comment]
>  But that's problematic when I'm building software for others to use

Are you wrapping the code ? How comes that the prompt happens before the `.Rprofile` or even `.Renviron` is loaded ? 

Just trying to understand the situation better. The env var solved it for me at the time.

**Comment by t-kalinowski** [comment]
I don't quite understand, what is causing reticulate to initialize Python?

**Comment by cderv** [comment]
Thanks I understand better this part now. 

> But the problem is that calling client <- DominoDataR::datasource_client() goes smoothly, and only after restarting R session I get the prompt, so this would require Renviron/Rprofile settings, which is too intrusive.

What I don't get is what would make the use of `client <- DominoDataR::datasource_client()` do something that would impact the restarting of R. 

It feels like a caching issue of some sort in the IDE maybe, seeing a python object from previous session before restarting (because it is trying to restore state ?). Something with the IDE maybe then 🤔

**Comment by daattali** [comment]
The IDE could be a contributing factor of this issue, because if the object isn't in my environment when restarting (if I remove it, or simply make the call without assignig it to a variable), then there's no issue.

**Comment by t-kalinowski** [comment]
To help track it down, you could place this in your .Rprofile:
```r
trace(reticulate:::initialize_python, quote(print(rlang::trace_back())))
```

**Comment by daattali** [comment]
Here is the console output after placing that line in my Rprofile:

```r
Restarting R session...

Tracing function "initialize_python" in package "reticulate
(not-exported)"
[1] "initialize_python"
> client <- DominoDataR::datasource_client()
Tracing initialize_python(required_module, use_environment) on entry 
     ▆
  1. └─base::loadNamespace(x)
  2.   └─base (local) runHook(".onLoad", env, package.lib, package)
  3.     ├─base::tryCatch(fun(libname, pkgname), error = identity)
  4.     │ └─base (local) tryCatchList(expr, classes, parentenv, handlers)
  5.     │   └─base (local) tryCatchOne(expr, names, parentenv, handlers[[1L]])
  6.     │     └─base (local) doTryCatch(return(expr), name, parentenv, handler)
  7.     └─DominoDataR (local) fun(libname, pkgname)
  8.       └─DominoDataR:::py_select_interpreter()
  9.         └─reticulate::py_available(initialize = TRUE)
 10.           ├─base::tryCatch(...)
 11.           │ └─base (local) tryCatchList(expr, classes, parentenv, handlers)
 12.           │   └─base (local) tryCatchOne(expr, names, parentenv, handlers[[1L]])
 13.           │     └─base (local) doTryCatch(return(expr), name, parentenv, handler)
 14.           └─reticulate:::ensure_python_initialized()
 15.             └─reticulate:::initialize_python(required_module, use_environment)

Restarting R session...

Tracing function "initialize_python" in package "reticulate
(not-exported)"
[1] "initialize_python"
Tracing initialize_python(required_module, use_environment) on entry 
    ▆
 1. └─.rs.describeObject(`<env>`, "client", TRUE)
 2.   └─.rs.reticulate.describeObject(objName, env)
 3.     └─reticulate::import_builtins(convert = TRUE)
 4.       └─reticulate:::ensure_python_initialized()
 5.         └─reticulate:::initialize_python(required_module, use_environment)
No non-system installation of Python could be found.
Would you like to download and install Miniconda?
Miniconda is an open source environment management system for Python.
See https://docs.conda.io/en/latest/miniconda.html for more details

Would you like to install Miniconda? [Y/n]:
```

**Comment by cderv** [comment]
It seems to come from their onLoad setting (https://github.com/dominodatalab/DominoDataR/blob/44c028a93cb9b2dc4784cc4e584f7116adedf9a9/R/zzz.R#L1-L3)

They are trying to install Miniconda if no python is found https://github.com/dominodatalab/DominoDataR/blob/44c028a93cb9b2dc4784cc4e584f7116adedf9a9/R/python.R#L19-L23
```python
  # If no Python is present (or not in the expected place), then install MiniConda.
  #
  if (!reticulate::py_available(initialize = TRUE)) {
    try(reticulate::install_miniconda())
  }
```

So the message comes from there probably.

**Comment by t-kalinowski** [comment]
I think the prompt after the 2nd restart indicates an IDE issue. It seems the IDE is initializing python during its attempt to generate a description for the env pane of a python object restored from .RData (i.e., a null ptr).

**Comment by daattali** [comment]
I can provide you with credentials (username/password) to a system where this issue is happening with every image new rstudio image that gets created. Would it be helpful for you if I give you access to debug? If you email me I can give you the credentials privately.

Or are you saying this is not a reticulate problem and not going to be solved by reticulate, and I should bring it up with the IDE instead?

**Comment by daattali** [comment]
If it is indeed an IDE issue, then would we expect this issue to happen with any code that saves a similar reticulate object?

**Comment by daattali** [comment]
@t-kalinowski I understand that this was fixed in RStudio. Do you know which IDE version this fix will be in?

**Comment by t-kalinowski** [comment]
I see Kevin already replied here: https://github.com/rstudio/rstudio/issues/13109#issuecomment-1544307867  :)

> It will be in Mountain Hydrangea (the upcoming release slated for end of this May)
