### ISSUE TITLE
Export a conda environment as a yaml and import from it

### ISSUE THREAD

**Issue by chainsawriot** [rstudio/reticulate#779]
One can export a conda environment as a yaml

```bash
conda activate my_conda
conda env export > my_conda.yaml
```

and then import from it to create a new conda environment

```bash
conda env create -f my_conda.yaml
```

(optionally with -n and -p to bypass the envname and path inscribed in the yaml)

This feature makes a lot of sense for reproducible analysis and could be a part of reticulate, namely: `conda_create` (add a `file` argument) etc. Maybe a new function `conda_export` makes sense too.

If someone seconds it, I would make a pull request.

**Comment by bschilder** [comment]
@chainsawriot I would definitely find this helpful. I include yaml files with all of my R packages so that the associated envs can be installed using the link. See [here for a number of examples](https://bschilder.github.io/scKirby/articles/conda.html).

For users unfamiliar with conda, it would be even better if I could install the non-R dependencies (Python, CLI) with a reticulate function. 

Thanks so much in advance!

**Comment by kevinushey** [comment]
This is now implemented in the development version of `reticulate`. You can use `conda_export()` to export an environment, and `conda_create(environment = <...>)` to create a new environment based on that export. For example:

```
library(reticulate)
conda_create("test-export", packages = "numpy")
conda_export("test-export", file = "environment.yml")
conda_create("test-export-clone", environment = "environment.yml")
```

Sorry it took so long!

**Comment by bschilder** [comment]
@kevinushey , amazing! thank you!!
