### ISSUE TITLE
Autoconfiguration when user already have conda installed

### ISSUE THREAD

**Issue by dfalbel** [rstudio/reticulate#789]
On Windows, when you freshly install R and the Anaconda distribution, and you run any 

```
reticulate::py_install()
```

You'll get prompted to install miniconda. If you opt-out (because you already have conda) you will get the error:

```
Error: Installing Python packages into a virtualenv is not supported on Windows
```

It happens because the discovered python is: `C:/Users/dfalbel/anaconda3/python.exe`
And the `python_info` the function we use to find the env type is returning:

```
reticulate:::python_info(reticulate::py_config()$python)
$python
[1] "C:/Users/dfalbel/anaconda3/Scripts/python.exe"

$type
[1] "virtualenv"

$root
[1] "C:/Users/dfalbel/anaconda3"
```

I could do a PR that checks for `conda_binary` around here:

https://github.com/rstudio/reticulate/blob/master/R/config.R#L172-L184

and in this case we also create the r-reticulate environment using the conda installation found:

https://github.com/rstudio/reticulate/blob/master/R/config.R#L188-L195

What do you think?

**Comment by kevinushey** [comment]
> It happens because the discovered python is: C:/Users/dfalbel/anaconda3/python.exe

Shouldn't this be finding and using a Conda environment instead? (the fact that this Python is classified as a virtual environment seems wrong as well)

Or, we should at least be prompting to creating a Conda environment to use with the existing Conda installation, rather than binding to the root Python executable.
