### ISSUE TITLE
Checking Python package version triggering winbuilder NOTE on R-devel

### ISSUE THREAD

**Issue by ethanwhite** [rstudio/reticulate#814]
In an R package we added a function for checking if the version of the wrapped Python package is sufficiently up-to-date.

https://github.com/ropensci/rdataretriever/blob/486bcf3a14be79ea398b93ffb99474e38de94adc/R/rdataretriever.R#L173-L196

This function is called in `.onLoad`, wrapped inside the recommended `try` block after `reticulate::import`:

https://github.com/ropensci/rdataretriever/blob/486bcf3a14be79ea398b93ffb99474e38de94adc/R/rdataretriever.R#L768-L774

This tests fine locally using `R CMD check` with `--as-cran` and passes on winbuilder, except for Windows on R-devel, which returns a NOTE:

```
Warning in system2(command = python, args = paste0("\"", config_script,  :
  running command '"C:/Users/ligges/AppData/Local/r-miniconda/envs/r-reticulate/python.exe" "d:/RCompile/CRANpkg/lib/4.1/reticulate/config/config.py"' had status 2

A namespace must be able to be loaded with just the base namespace
loaded: otherwise if the namespace gets loaded by a saved object, the
session will be unable to start.

Probably some imports need to be declared in the NAMESPACE file.
```

Link to winbuilder output: https://win-builder.r-project.org/incoming_pretest/rdataretriever_3.0.0_20200804_163723/Windows/00check.log

Any advice for avoiding this note or direction to guidance on better practice for performing version checks of associated Python packages would be greatly appreciated.

Linking to the issue in our repo: https://github.com/ropensci/rdataretriever/issues/242

**Comment by kevinushey** [comment]
My main concern here is that you're basically forcing Python to be initialized when your package is loaded, whereas users should normally be able to defer load of Python until they're "ready" to load it.

The warning here suggests that `reticulate` isn't able to initialize Python on the CRAN machine, but I don't know why.

**Comment by ethanwhite** [comment]
Thanks @kevinushey. Do you generally recommend against having this type of check at all in onLoad?

**Comment by kevinushey** [comment]
That's correct -- in general, R packages should avoid initializing Python on load if at all possible; normally Python initialization should be triggered explicitly by the user (e.g. because they called a package function that really does require Python to be loaded, or because they directly instructed reticulate to initialize Python).

I believe in this case, you could do the same by setting a module load hook. You can define your hook with:

```
setHook("reticulate::module::load", function(...) {
  # actions to perform after the module has been loaded
})
```

... but unfortunately it turns out there's a bug that makes this not work as expected. 😞

This has been fixed on master now, but unfortunately won't be useful in your case until `reticulate` is updated on CRAN.

Sorry for the terseness of my original reply. My general view is that debugging Python issues on CRAN machines is just not worth the effort, given the lack of insight we have into how Python is installed and configured on CRAN machines. I would advocate testing via CI systems, where we normally have more control over the system and at least have some ability to introspect on problems.

I realize it's not a very satisfying answer, but ... if you're able to disable these tests when using `reticulate` on Windows on CRAN, I'd recommend doing so.

**Comment by ethanwhite** [comment]
Thanks @kevinushey. This is really useful and definitely no worries on the initial reply.

We'll move this to a user-called function for this release and implement the module load hook method in the next round of development.
