### ISSUE TITLE
Persistence of Python variable named `r` across chunks

### ISSUE THREAD

**Issue by jjf234** [rstudio/reticulate#847]
Hi, I was redirected here from https://github.com/yihui/knitr/issues/1878.

It appears the scope of a variable named `r` does not persist across Python chunks. For example:

````
```{python}
r = 0
print(r)
```
````

Prints `0` as expected. But then the immediately following chunk:

````
```{python}
print(r)
```
````

Prints `<__main__.R object at 0x000001F1458F4B08>` instead.

Switching the variable name to something else, like `s`, works as expected though, i.e. prints `0` in both chunks above. Would be great to have similar behavior for variables named `r` too. Thanks.

**Comment by kcarnold** [comment]
As yihui said there: "The object r has a special meaning: https://rstudio.github.io/reticulate/articles/r_markdown.html#calling-r-from-python-1"

But: what about if the special object was called `R`? (`r` is currently an instance of a class called `R`; is there any use for the class separately from the instance?)

(Even if this is a good idea, it might be too troublesome to change because of backwards compatibility. For example, `reticulate` would have to conditionally inject the `r` object.)

**Comment by kevinushey** [comment]
I think it would be reasonable for `reticulate` to only inject the `r` object if there isn't already one defined.

Similarly, the `R` object doesn't need to be visible in the main module either.

**Comment by jjf234** [comment]
Thanks, Kevin. That sounds good. My use case is one-way, i.e. Python => R, so would make sense to only inject the `r` object if there isn't one already defined, as you suggest.

**Comment by kevinushey** [comment]
Thanks! Should be resolved via https://github.com/rstudio/reticulate/commit/fcd969e56bfc98d7fde6ac9fe0ccaae8f8ff34ab.
