### ISSUE TITLE
A function in SciPy.sparse cannot be used in reticulate

### ISSUE THREAD

**Issue by binxiangni** [rstudio/reticulate#85]
A function `load_npz` in SciPy.sparse cannot be used in `reticulate`. But `load_npz` does exist in [scipy.sparse](https://docs.scipy.org/doc/scipy/reference/generated/scipy.sparse.load_npz.html). 
```
> library(reticulate)
> sp <- import("scipy.sparse")
> py_has_attr(sp, "load_npz")
[1] FALSE
```

**Comment by jjallaire** [comment]
The problem is likely that reticulate is finding and using a version of Python that has an older scipy available. Your code works as expected when I am running against scipy 0.19.1.

You can confirm this with:

```r
sp <- import("scipy")
sp$`__version__`
```

And confirm which version of Python is being bound to with:

```r
py_config()
```

This article describes how to configure which version of Python is bound to: https://rstudio.github.io/reticulate/articles/versions.html
