### ISSUE TITLE
must set NUM_OMP_THREADS=1 when using sklearn with reticulate

### ISSUE THREAD

**Issue by vjcitn** [rstudio/reticulate#86]
I will try to create a reproducible example, but I wonder if there is an answer on
a priori grounds.  I am finding that I cannot use, e.g., sklearn.decomposition.IncrementalPCA
in reticulate, unless I set NUM_OMP_THREADS to 1 before starting R.  What aspects
of python and R configurations need to be known to diagnose this further?  If NUM_OMP_THREADS > 1, lots of computation occurs but it does not seem to progress as coded.  The base OS
in question is linux, anaconda python 2.7 in use.

**Comment by jjallaire** [comment]
I don't offhand know why this would be. I do know that if you pass an R function to Python code and the Python code calls it on another thread then that won't work (since R needs to run on the main thread) however I don't see anything in the interface for IncrementalPCA that suggests it takes an R function as input.

**Comment by vjcitn** [comment]
OK, thanks. I will see if it can be characterized more clearly.  Can close
for now.
