### ISSUE TITLE
Python shared library not found, potential issue when switching from Miniconda to Miniforge?

### ISSUE THREAD

**Issue by moldach** [rstudio/reticulate#952]
I was following instructions for [paired-programming with `R` in `VS Code`](https://ivelasq.rbind.io/blog/vscode-live-share/) which I believe may have switched `miniconda` for `miniforge`.

Now I'm getting the following error from {`reticulate`}:

First, I create a `conda` environment as follows:

```
$ conda create --name testenv python==3.6
```

Next, from `R` `console` I run:

```
> library(reticulate)
> use_condaenv("testenv")
> py_run_string("print(1)")
Error: Python shared library not found, Python bindings not loaded.
Use reticulate::install_miniconda() if you'd like to install a Miniconda Python environment.
```

Which is an odd error since the following tells me it's already installed:

```
> reticulate::install_miniconda()
Error: Miniconda is already installed at '/home/mtg/.local/share/r-miniconda'
```

How do I fix this?

### Potentially helpful information?

```
> py_discover_config()
python:         /home/mtg/.pyenv/shims/python
libpython:      [NOT FOUND]
pythonhome:     /home/mtg/.pyenv/versions/3.6.0:/home/mtg/.pyenv/versions/3.6.0
version:        3.6.0 (default, May 28 2020, 09:03:33)  [GCC 9.3.0]
numpy:          /home/mtg/.pyenv/versions/3.6.0/lib/python3.6/site-packages/numpy
numpy_version:  1.19.5

NOTE: Python version was forced by RETICULATE_PYTHON
```

**Comment by moldach** [comment]
This is [related to this posting](https://github.com/ranikay/shiny-reticulate-app/issues/12); here is what I've tried:

## Terminal

```
(base) mtg@mtg-ThinkPad-P53:~/r-projects/shiny-reticulate-app$ python3 -m venv ~/mattsNewENV
(base) mtg@mtg-ThinkPad-P53:~/r-projects/shiny-reticulate-app$ source ~/mattsNewENV/bin/activate
(mattsNewENV) (base) mtg@mtg-ThinkPad-P53:~/r-projects/shiny-reticulate-app$ python3 -m pip install --upgrade pip
Cache entry deserialization failed, entry ignored
Collecting pip
  Using cached https://files.pythonhosted.org/packages/fe/ef/60d7ba03b5c442309ef42e7d69959f73aacccd0d86008362a681c4698e83/pip-21.0.1-py3-none-any.whl
Installing collected packages: pip
  Found existing installation: pip 9.0.1
    Uninstalling pip-9.0.1:
      Successfully uninstalled pip-9.0.1
Successfully installed pip-21.0.1
(mattsNewENV) (base) mtg@mtg-ThinkPad-P53:~/r-projects/shiny-reticulate-app$ pip3 --version
pip 21.0.1 from /home/mtg/mattsNewENV/lib/python3.6/site-packages/pip (python 3.6)
(mattsNewENV) (base) mtg@mtg-ThinkPad-P53:~/r-projects/shiny-reticulate-app$ python3 -m pip install --upgrade virtualenv
```

> If you still get the same error, I'd recommend going in the virtualenv and confirming whether pip is installed correctly into the environment. 

Might as well just do this to confirm that the Python package `virtualenv` is contained within this created environment.

```
# Restart shell
(mattsNewENV) (base) mtg@mtg-ThinkPad-P53:~/mattsNewENV$ exec $SHELL
# Enter environmet
(base) mtg@mtg-ThinkPad-P53:~/mattsNewENV$ cd ~/mattsNewENV/
(base) mtg@mtg-ThinkPad-P53:~/mattsNewENV$ source bin/activate
# check for installed modules
(mattsNewENV) (base) mtg@mtg-ThinkPad-P53:~/mattsNewENV$ pip3 freeze
appdirs==1.4.4
distlib==0.3.1
filelock==3.0.12
importlib-metadata==3.4.0
importlib-resources==5.1.0
six==1.15.0
typing-extensions==3.7.4.3
virtualenv==20.4.2
zipp==3.4.0
```

We can see that `virtualenv==20.4.2` is available in the environment, so next we make changes:

### Change `.Rprofile` included with repo

```
# Edit this name if desired when starting a new app
VIRTUALENV_NAME = 'shiny-reticulate-test'
```

Finally, Save, Restart R (Ctrl + Shift + F10), and then try and run the app.

### RunApp

```
> shiny::runApp()
Loading required package: shiny

Listening on http://127.0.0.1:7450

Attaching package: ‘DT’

The following objects are masked from ‘package:shiny’:

    dataTableOutput, renderDataTable

Warning: Error in : Tools for managing Python virtual environments are not installed.

Install pip with:
$ curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
$ python3 get-pip.py

Install virtualenv with:
$ python3 -m pip install --upgrade --user virtualenv


  50: stop
  49: virtualenv_module
  48: reticulate::virtualenv_create
  47: server [/home/mtg/r-projects/shiny-reticulate-app/server.R#18]
Error : Tools for managing Python virtual environments are not installed.

Install pip with:
$ curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
$ python3 get-pip.py

Install virtualenv with:
$ python3 -m pip install --upgrade --user virtualenv
```

**Comment by myoung3** [comment]
In your first post, it's possible that two different miniconda installations exist. In R, try `reticulate::conda_list()`. this will display all the conda environments detected by reticulate and their corresponding directories. I'm guessing testenv won't be listed since reticulate hasn't detected the miniconda installation that testenv is actually in.  When you type `conda` in the system, the system uses the default conda installation, but reticulate may use other default arcane and mysterious methods for finding conda.
In any case, you can tell reticulate which miniconda installation to use via `use_miniconda` (you need to run this at the start of every session) or set the environment variable RETICULATE_MINICONDA_PATH (which should point to a directory not a binary). 

In your second post, I'm pretty sure you want to add all environment variables to .Renviron, not .Rprofile. The  .Rprofile file is just an .R file that that runs before startup (but after environment variables are set). See `?Startup` or https://rstats.wtf/r-startup.html You can verify that an environment variable is set with Sys.getenv("RETICULATE_PYTHON"). You're also using virtual environments here, which is fine. But you need to choose between a conda environment and a virtual environment.


In general I've found that the surest way to get reticulate working with a conda environment in a miniconda installation that reticulate did not itself install is to set the three following environment variables in your global (or project-local) .Renviron file:
RETICULATE_PYTHON = <path to the binary of python inside of your miniconda environment>
RETICULATE_MINICONDA_PATH = <path to the directory corresponding to the miniconda installation that contains your environment>
RETICULATE_PYTHON_ENV= <name of the environment>

**Comment by kevinushey** [comment]
What if you use:

```
use_condaenv("testenv", required = TRUE)
```

instead?

**Comment by moldach** [comment]
> In your first post, it's possible that two different `miniconda` installations exist. In R, try `reticulate::conda_list()`. this will display all the conda environments detected by reticulate and their corresponding directories. 

```
> reticulate::conda_list()
              name
1     r-reticulate
2        anaconda3
3            build
4           cnvkit
5         cnvn_env
6        snakemake
7       svviz_venv
8       miniforge3
9         MToolBox
10       r-console
11 shinyReticulate
12         testenv
                                                            python
1  /home/mtg/.local/share/r-miniconda/envs/r-reticulate/bin/python
2                                   /home/mtg/anaconda3/bin/python
3                        /home/mtg/anaconda3/envs/build/bin/python
4                       /home/mtg/anaconda3/envs/cnvkit/bin/python
5                     /home/mtg/anaconda3/envs/cnvn_env/bin/python
6                    /home/mtg/anaconda3/envs/snakemake/bin/python
7                   /home/mtg/anaconda3/envs/svviz_venv/bin/python
8                                  /home/mtg/miniforge3/bin/python
9                    /home/mtg/miniforge3/envs/MToolBox/bin/python
10                  /home/mtg/miniforge3/envs/r-console/bin/python
11            /home/mtg/miniforge3/envs/shinyReticulate/bin/python
12                    /home/mtg/miniforge3/envs/testenv/bin/python
```

> I'm guessing `testenv` won't be listed since `reticulate` hasn't detected the miniconda installation that testenv is actually in. 

We see that `testenv` is listed by `reticulate` here - so _what's going on?_

> When you type `conda` in the system, the system uses the default conda installation, but reticulate may use other default arcane and mysterious methods for finding conda.

Let's uncover the 🔮! 
I remember setting up Python in reticulate was a big challenge on a (different) work computer two years ago - I wish it was easier in 2021...

> In any case, you can tell reticulate which miniconda installation to use via `use_miniconda` (you need to run this at the start of every session) or set the environment variable RETICULATE_MINICONDA_PATH (which should point to a directory not a binary).

If I start a new RStudio session and do the following before trying to run the app 
`Sys.setenv(RETICULATE_MINICONDA_PATH = "/home/mtg/.local/share/r-miniconda")` I get the same error.

**Comment by myoung3** [comment]
Your `list_conda()` output tells you that `testenv` is an environment in the `/home/mtg/miniforge` conda installation. Maybe try `use_miniconda("/home/mtg/miniforge3"); use_condaenv("testenv")`? (Note that `Sys.setenv` doesn't write to `.Renviron`, so it really no different than `use_miniconda`. If you want this set up permanently, you need to edit `.Renviron` and to my knowledge `reticulate` doesn't offer a convenience function that writes to `.Renviron`. If you don't want to modify `~/.Renviron` (ie if you want other projects to use other python binaries/conda installations/environments), you can create a project-specific `.Renviron` file which will supersede `~/.Renviron`. )

If the above doesn't work...

Maybe try specifying the filepath instead of the environment name `use_condaenv("/home/mtg/miniforge3/envs/testenv")`?

**Comment by moldach** [comment]
Removed `miniforge` and `r-minconda` directories to try to start _fresh_.

Open `RStudio` and `install_miniconda()` produces an error:

```
> reticulate::install_miniconda()
* Downloading 'https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh' ...
trying URL 'https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh'
Content type 'application/x-sh' length 94235922 bytes (89.9 MB)
==================================================
downloaded 89.9 MB

* Installing Miniconda -- please wait a moment ...
/tmp/RtmpMhU7F2/Miniconda3-latest-Linux-x86_64.sh: 9: export: /usr/lib/jvm/java-8-openjdk-amd64/lib/server: bad variable name
Error: miniconda installation failed [exit code 2]
```

Check which version of Python is available:

```
$ which python3
/home/mtg/.pyenv/shims/python3
```
Then try and [use the `use_python()` command (instead of `use_conda()`)](https://rstudio.github.io/reticulate/index.html) - here I also experience an error:

```
> library(reticulate)
> reticulate::use_python("/home/mtg/.pyenv/shims/python")
> os <- import("os")
Error: Python shared library not found, Python bindings not loaded.
Use reticulate::install_miniconda() if you'd like to install a Miniconda Python environment.
```

### System info

```
$ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.2 LTS"
```

**Comment by kevinushey** [comment]
By default, `pyenv` installs copies of Python without the Python shared library available, which causes problems for reticulate. See https://github.com/pyenv/pyenv/wiki#how-to-build-cpython-with---enable-shared for more details.

I have no idea why the Miniconda installer is failing on your machine.

**Comment by moldach** [comment]
> I have no idea why the Miniconda installer is failing on your machine.

Okay no worries, a manual `miniconda` installation followed by `reticulate::use_condaenv("envName")` seems to be working now.

Thanks for sharing the link on `pyenv` @kevinushey and for the help troubleshooting @myoung3 !

**Comment by iwensu0313** [comment]
Thank you @kevinushey for the link to building cpython w/ `--enable-shared`! That fixed my problem. I use `pyenv` to manage my Pythons on my MacOS and I didn't want to switch to `miniconda`, which many solutions recommended.

**Comment by t-kalinowski** [comment]
FYI, you can also use `reticulate::install_python()`, which wraps `pyenv` under the hood and automatically sets `--enable-shared` for you.
